import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToastWrapper from "@/components/ToastWrapper";
import ReduxProvider from "@/redux/ReduxProvider";
import PersistGateProvider from "@/redux/PersistGateProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Todoboard Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#121212] text-white`}
      >
        <ToastWrapper>
          <ReduxProvider>
            <PersistGateProvider>{children}</PersistGateProvider>
          </ReduxProvider>
        </ToastWrapper>
        <div id="modal-root" />
      </body>
    </html>
  );
}
